# Generated by Django 6.0.6 on 2026-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Supervisor (всі підрозділи)'),
        ),
    ]
